### ISSUE TITLE
Deactivation of warning "duplicate sequence" possible?

### ISSUE THREAD

**Issue by Kellermeister1976** [iSorp/macro-executor#10]
for writing axis parameters via the macro the n-number is used multiple times.

G10L52;
N2514P1R0;
N2514P2R0;               
G11;

the double use of N2514 results in a warning. how can this warning be deactivated? or is there a possibility that the plugin recognizes that parameters are written here and a multiple number is allowed?

thanks a lot for your great work!!!

**Comment by iSorp** [comment]
@Kellermeister1976 currently there is no recognition for sequence number checks in a G10/G11 block.  You can ignore this warning by setting the following lint rule:
```
    "macro.lint": {
        "rules": {
            "duplicateSequence": "ignore"
        }
    }
```

**Comment by Kellermeister1976** [comment]
thanks for the settings sequence above. it works and solves my problem perfectly. thanks for your great support!
