### ISSUE TITLE
Error "macro-newlineexpected" in message definition since update to v0.3.1

### ISSUE THREAD

**Issue by Kellermeister1976** [iSorp/macro-executor#14]
since update to version 0.3.1 an error is displayed at the message definitions.

![image](https://user-images.githubusercontent.com/74239333/113896385-2bdca300-97ca-11eb-9410-0183287402af.png)

how can i solve this problem?

thanks for your great work with this extension and for your support.

**Comment by iSorp** [comment]
Fixed in https://github.com/iSorp/macro-executor/commit/0bd2d267fa285bb70ddb3d58ad2fa72d61c93257
