### ISSUE TITLE
Source Text Document Formatting support

### ISSUE THREAD

**Issue by Futoro** [iSorp/macro-executor#19]
Currently this extension does a great support at supporting developers with Fanuc Macros. However it does not support formatting entire source text documents. The required lsp endpoint to implement: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_formatting.

**Comment by iSorp** [comment]
A simple formatting provider has been added in [v0.4.0](https://github.com/iSorp/macro-executor/releases/tag/v0.4.0).
