### ISSUE TITLE
DPRINT/BPRINT Symbols not allowed

### ISSUE THREAD

**Issue by Futoro** [iSorp/macro-executor#21]
Some symbols (*, - and +) in a DPRINT/BPRINT are marked as incorrect input, but the compiler can process them without problems.
See example images.
![image](https://user-images.githubusercontent.com/79048803/167120119-b7488b33-0c0d-451c-b6ef-20cd570ed817.png)
![image](https://user-images.githubusercontent.com/79048803/167120263-9c849432-550b-4f2a-8480-111c56717870.png)
![image](https://user-images.githubusercontent.com/79048803/167120329-c9d41a4c-8200-4ae8-b159-653cc3045828.png)

**Comment by iSorp** [comment]
Thanks for the feedback, I‘ll need some time to fix it.
