### ISSUE TITLE
Char $ in Variable Name

### ISSUE THREAD

**Issue by Kellermeister1976** [iSorp/macro-executor#5]
this is a really cool plug-in ... thanks for the development

In our Macro Project, there are the most variable names with char '$' in the name.
for example ASSIST$DRS_ACT

$ in name does not work for me, the variables are not recognized. is there a way to use the character $ in the variable name?

**Comment by iSorp** [comment]
Thanks for your feedback! I added '$' to the allowed symbol chars.
