### ISSUE TITLE
error message "assignment on constant" without brackets

### ISSUE THREAD

**Issue by Kellermeister1976** [iSorp/macro-executor#6]
pcode definition:
@CYCCALL$G004     17052

assignment in src code:
#CYCCALL$G004 = 1

this assignment shows error "assignment on a constant". when i programm "#[CYCCALL$G004] = 1" it works.

it is possible to support also "#CYCCALL$G004 = 1" (without brackets) ?

we also used a indexed call of a value like this:
#COR$TOOL_XF1<[#SC$APLA-1]*CONST$COR_TOOL_LENGTH> = 3;
we also need this syntax very intensively in our project.

we use this syntax without brackets over the whole big project. an adaptation of the syntax is unfortunately not easy to implement.

i would be very happy if this adaptation could be implemented.

thanks a lot for this great plugin

**Comment by iSorp** [comment]
The easiest way to achieve your needs is to change the lint rule **assignmentConstant** in your settings.

    "macro.lint": {
        "rules": {
            "assignmentConstant": "ignore"
        }
    }

**Comment by Kellermeister1976** [comment]
I have tested it and it works. This solution fits for me. thank you very much for the fast answer. the support is great!!!
