### ISSUE TITLE
Syntax error in line in definition file

### ISSUE THREAD

**Issue by Kellermeister1976** [iSorp/macro-executor#9]
Line in definition file:
@SKIP$DEACTIVATE     	A#0B#0   ->  plugin shows an error "unknown symbol"

Line in source file:
SKIP$PATH1 SKIP$DEACTIVATE U1;   -> shows no error

the compiler support this syntax in the definition file, is it always possible that the plugin supports this syntax also?

thank you very much for this great plugin!

**Comment by iSorp** [comment]
The issue has been fixed in the latest release
